name: Code quality

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3
      - name: Running tests
        shell: pwsh
        run: ./pester.ps1
