name: Main

on:
  pull_request:
  push:
    branches:
      - 'main'
  release:
    types:
      - 'published'

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  analysis:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/analysis.yaml

  publish:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs:
      - test
      - static-analysis
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
