name: Publish

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      PUBLISH_KEY:
        description: 'PowerShell Gallery API key'
        required: true

jobs:
  main:
    runs-on: ubuntu-22.04
    environment: PowerShell Gallery
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4

      - name: Publishing to PowerShell Gallery
        shell: pwsh
        working-directory: ./scripts
        run: ./publish.ps1 -NugetAPIKey '${{ secrets.PUBLISH_KEY }}' -Verbose
