name: Publish

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      PUBLISH_KEY:
        description: 'PowerShell Gallery API key'
        required: true

jobs:
  main:
    runs-on: ubuntu-22.04
    environment: PowerShell Gallery
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3
      - name: Preparing publish folder
        shell: pwsh
        working-directory: ./scripts
        run: ./build.ps1
      - name: Publishing to PowerShell Gallery
        shell: pwsh
        run: Publish-Module -Path ./publish/DevOpTools -NugetAPIKey '${{ secrets.PUBLISH_KEY }}' -Verbose
