name: Test

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3
      - name: Running tests
        shell: pwsh
        working-directory: ./scripts
        run: ./test.ps1
