name: Test

on:
  workflow_call:

jobs:
  pester:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4

      - name: Running tests
        shell: pwsh
        working-directory: ./scripts
        run: ./test.ps1

  publish:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: pwsh
        working-directory: ./scripts
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4

      - name: Registering local PowerShell repository
        run: |
          $repoPath = '~/psrepo'
          New-Item -Path $repoPath -ItemType Directory -Force
          $repoPath = Resolve-Path -Path $repoPath

          Register-PSRepository -Name local `
            -SourceLocation "$repoPath" `
            -PublishLocation "$repoPath" `
            -InstallationPolicy Trusted

      - name: Publishing to local repository
        run: ./publish.ps1 -Local -Verbose

      - name: Installing from local repository
        run: Install-Module -Name DevOpTools -Repository local -Scope CurrentUser

      - name: Running tests on locally installed version
        run: ./test.ps1 -Installed
